"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Собранный React (Vite) фронт. Локально — plume/frontend/dist; на сервере тот же
# относительный путь: site/backend/ (BASE_DIR) и site/frontend/dist рядом.
FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'

# Локальная разработка: переменные окружения из backend/.env (не в репозитории).
load_dotenv(BASE_DIR / '.env')


def env(key, default=None):
    return os.environ.get(key, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', 'django-insecure-dev-only-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # WhiteNoise: отключает раздачу статики dev-сервером, чтобы поведение совпадало с продом.
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'corsheaders',
    # local
    'plume',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise сразу после SecurityMiddleware: раздаёт /static/ на shared-хостинге
    # (Apache Alias на reg.ru shared недоступен — грабля соседнего проекта).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # index.html собранного фронта — его отдаёт SPA catch-all во config/urls.py.
        'DIRS': [FRONTEND_DIST],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# MySQL 8.0.25 (паритет с целевым хостингом). Локально — в Docker (см.
# docker-compose.yml). Драйвер — PyMySQL (см. config/__init__.py), чистый Python,
# без сборки; сама СУБД — настоящий MySQL, что важно для констрейнтов модели.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', 'plume'),
        'USER': env('DB_USER', 'plume'),
        'PASSWORD': env('DB_PASSWORD', 'plume'),
        'HOST': env('DB_HOST', '127.0.0.1'),
        'PORT': env('DB_PORT', '3307'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # STRICT — чтобы локально ловить те же ошибки данных, что и на проде.
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
#
# Vite собирает фронт с base='/static/' (см. frontend/vite.config.ts), поэтому весь
# dist попадает под STATIC_URL и раздаётся WhiteNoise. Хранилище — БЕЗ манифеста:
# у ассетов Vite уже свои контент-хэши в именах, а ManifestStaticFilesStorage
# перехэшировал бы их (ссылки в index.html побились бы) и падал бы на url(...) внутри
# CSS-комментариев (грабля соседнего проекта). Сжатие (gz/br) WhiteNoise оставляем.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [FRONTEND_DIST]

# Django 5.1+ убрал STATICFILES_STORAGE/DEFAULT_FILE_STORAGE — только STORAGES.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework — в волне 1 отдаём только read-only проекции движка.
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# CORS — локальный фронт Vite (см. frontend/). На проде фронт отдаёт сам Django
# (SPA с того же origin), так что CORS там не нужен — переменную можно оставить
# пустой. Пустые элементы отсекаем, иначе '' даёт corsheaders.E013 и падает check.
CORS_ALLOWED_ORIGINS = [
    o for o in env(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',') if o
]


# --- Прод-настройки (включаются при DEBUG=False) ---
# Reg.ru shared: сайт за Apache/Passenger с терминацией SSL на прокси. Django должен
# понимать, что запрос пришёл по https (иначе secure-cookie и редиректы врут).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Django 4.2 требует https-origin в списке доверенных для POST в /admin/.
    # Домен(ы) задаются в .env на сервере, в репозиторий не попадают.
    CSRF_TRUSTED_ORIGINS = [
        o for o in env('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o
    ]
