# Generated by Django 6.0.6 on 2026-07-31 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=128, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('inn', models.CharField(blank=True, default='', max_length=16, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('kind', models.CharField(blank=True, default='', max_length=32, verbose_name='вид')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='бюджет на материалы')),
                ('kind', models.CharField(choices=[('external', 'Внешний (НИР/контракт)'), ('internal_stock', 'Собственный склад (белые)'), ('internal_writeoff', 'Свободные неучтённые (серые)')], default='external', max_length=20, verbose_name='вид')),
                ('locked', models.BooleanField(default=False, verbose_name='зафиксирован')),
                ('started', models.DateField(blank=True, null=True, verbose_name='начат')),
                ('closed', models.DateField(blank=True, null=True, verbose_name='закрыт')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('native', models.BooleanField(default=False, verbose_name='производимое')),
                ('locked', models.BooleanField(default=False, verbose_name='зафиксировано')),
                ('synced', models.BooleanField(default=False, verbose_name='из библиотеки')),
                ('uom', models.CharField(default='шт', max_length=32, verbose_name='ед. изм.')),
                ('temperature', models.CharField(blank=True, default='', max_length=64, verbose_name='температурный диапазон')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='оценочная стоимость')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='plume.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'изделие',
                'verbose_name_plural': 'изделия',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='plume.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='plume.item')),
            ],
            options={
                'verbose_name': 'строка BOM',
                'verbose_name_plural': 'строки BOM',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='код')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание')),
                ('locked', models.BooleanField(default=False, verbose_name='зафиксирована')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата (начало переговоров)')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='plume.counterparty', verbose_name='контрагент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('projects', models.ManyToManyField(blank=True, related_name='procurements', to='plume.project', verbose_name='охват (проекты)')),
            ],
            options={
                'verbose_name': 'закупка (план)',
                'verbose_name_plural': 'закупки (план)',
            },
        ),
        migrations.CreateModel(
            name='ProcurementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во (итог)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.item')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.procurement')),
            ],
            options={
                'verbose_name': 'строка закупки',
                'verbose_name_plural': 'строки закупки',
            },
        ),
        migrations.CreateModel(
            name='ProjectDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='plume.project')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demanded_in', to='plume.item')),
            ],
            options={
                'verbose_name': 'потребность проекта',
                'verbose_name_plural': 'потребности проектов',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='код')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание')),
                ('locked', models.BooleanField(default=False, verbose_name='зафиксирован')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата (оформление)')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plume.counterparty', verbose_name='контрагент')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plume.procurement', verbose_name='закупка-план')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plume.project', verbose_name='проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='заказано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='plume.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.purchase')),
            ],
            options={
                'verbose_name': 'строка заказа',
                'verbose_name_plural': 'строки заказа',
            },
        ),
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('receipt', 'Поставка'), ('kitting', 'Комплектация'), ('inventory', 'Инвентаризация'), ('requisition', 'Требование'), ('transfer', 'Передача'), ('writeoff', 'Списание'), ('relocation', 'Перемещение')], default='', max_length=16, verbose_name='вид ордера')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='код')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание')),
                ('locked', models.BooleanField(default=False, verbose_name='зафиксирован')),
                ('number', models.CharField(blank=True, default='', max_length=64, verbose_name='номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='кол-во образцов')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='причина')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='plume.counterparty', verbose_name='контрагент')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='plume.project', verbose_name='проект')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='plume.purchase')),
                ('target_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kittings', to='plume.item', verbose_name='прибор-цель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'ордер',
                'verbose_name_plural': 'ордера',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='рождённое кол-во')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='цена / себестоимость')),
                ('part_number', models.CharField(blank=True, default='', max_length=128, verbose_name='part number')),
                ('lot_name', models.CharField(blank=True, default='', max_length=255, verbose_name='название партии')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='plume.item')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='plume.lot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='plume.project', verbose_name='home-проект')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='plume.stockdocument', verbose_name='ордер-origin')),
            ],
            options={
                'verbose_name': 'партия',
                'verbose_name_plural': 'партии',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='файл')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='имя файла')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='описание')),
                ('size', models.IntegerField(default=0, verbose_name='размер, байт')),
                ('content_type', models.CharField(blank=True, default='', max_length=64, verbose_name='тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.counterparty')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.item')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.procurement')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.project')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.purchase')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.stockdocument', verbose_name='ордер-владелец')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'verbose_name': 'инвентаризация',
                'verbose_name_plural': 'инвентаризации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Kitting',
            fields=[
            ],
            options={
                'verbose_name': 'комплектация',
                'verbose_name_plural': 'комплектации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Relocation',
            fields=[
            ],
            options={
                'verbose_name': 'перемещение',
                'verbose_name_plural': 'перемещения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
            ],
            options={
                'verbose_name': 'требование',
                'verbose_name_plural': 'требования',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
            ],
            options={
                'verbose_name': 'передача',
                'verbose_name_plural': 'передачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='Writeoff',
            fields=[
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'списания',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('plume.stockdocument',),
        ),
        migrations.CreateModel(
            name='StockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во (со знаком: − расход)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата (пайка)')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='отображаемое имя (накладная)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.stockdocument', verbose_name='ордер-владелец')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines', to='plume.lot', verbose_name='лот (расходуемый источник)')),
            ],
            options={
                'verbose_name': 'строка движения',
                'verbose_name_plural': 'строки движения',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEIPT', 'Приход'), ('ISSUE', 'Расход')], max_length=16, verbose_name='тип')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во (со знаком)')),
                ('source_type', models.CharField(max_length=32, verbose_name='тип документа-источника')),
                ('source_id', models.IntegerField(verbose_name='id документа-источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='штамп вставки')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='plume.lot')),
            ],
            options={
                'verbose_name': 'движение склада',
                'verbose_name_plural': 'движения склада',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=32, verbose_name='тема интерфейса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('synced', False), ('native', False), _connector='OR'), name='item_synced_implies_not_native'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('synced', False), ('locked', False), _connector='OR'), name='item_synced_implies_not_locked'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('locked', False), ('category__isnull', False), _connector='OR'), name='item_locked_has_category'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('parent', 'component'), name='bomline_uniq_parent_component'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('locked', False), ('contractor__isnull', False), _connector='OR'), name='purchase_locked_has_contractor'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.UniqueConstraint(fields=('purchase', 'item'), name='purchaseline_uniq_purchase_item'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'receipt'), _negated=True), ('locked', False), ('contractor__isnull', False), _connector='OR'), name='doc_locked_receipt_has_contractor'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'kitting'), _negated=True), ('locked', False), models.Q(('target_item__isnull', False), ('qty__isnull', False)), _connector='OR'), name='doc_locked_kitting_has_target'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('receipt', 'transfer')), ('contractor__isnull', True), _connector='OR'), name='doc_contractor_only_own_kinds'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'receipt'), ('purchase__isnull', True), _connector='OR'), name='doc_purchase_only_receipt'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'kitting'), models.Q(('target_item__isnull', True), ('qty__isnull', True)), _connector='OR'), name='doc_target_only_kitting'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('document__isnull', True), ('project__isnull', True), ('procurement__isnull', True), ('purchase__isnull', True), ('counterparty__isnull', True)), models.Q(('document__isnull', False), ('item__isnull', True), ('project__isnull', True), ('procurement__isnull', True), ('purchase__isnull', True), ('counterparty__isnull', True)), models.Q(('project__isnull', False), ('item__isnull', True), ('document__isnull', True), ('procurement__isnull', True), ('purchase__isnull', True), ('counterparty__isnull', True)), models.Q(('procurement__isnull', False), ('item__isnull', True), ('document__isnull', True), ('project__isnull', True), ('purchase__isnull', True), ('counterparty__isnull', True)), models.Q(('purchase__isnull', False), ('item__isnull', True), ('document__isnull', True), ('project__isnull', True), ('procurement__isnull', True), ('counterparty__isnull', True)), models.Q(('counterparty__isnull', False), ('item__isnull', True), ('document__isnull', True), ('project__isnull', True), ('procurement__isnull', True), ('purchase__isnull', True)), _connector='OR'), name='attachment_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot'], name='plume_stock_lot_id_7c3612_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location'], name='plume_stock_locatio_3b042c_idx'),
        ),
    ]
