# Generated by Django 4.2.30 on 2026-06-30 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='№ акта')),
                ('date', models.DateField(verbose_name='дата')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='примечание')),
            ],
            options={
                'verbose_name': 'инвентаризация',
                'verbose_name_plural': 'инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='артикул')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('kind', models.CharField(choices=[('device', 'Изделие'), ('component', 'Компонент'), ('material', 'Материал')], default='component', max_length=16, verbose_name='вид')),
                ('uom', models.CharField(default='шт', max_length=32, verbose_name='ед. изм.')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='оценочная стоимость')),
                ('is_manufactured', models.BooleanField(default=False, verbose_name='производимое')),
                ('active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'изделие',
                'verbose_name_plural': 'изделия',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Kitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во образцов')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата открытия')),
                ('status', models.CharField(choices=[('wip', 'В работе'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='wip', max_length=16, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'комплектация',
                'verbose_name_plural': 'комплектации',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('kind', models.CharField(blank=True, default='', max_length=32, verbose_name='вид')),
            ],
            options={
                'verbose_name': 'место хранения',
                'verbose_name_plural': 'места хранения',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='рождённое кол-во')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='цена / себестоимость')),
                ('received_name', models.CharField(blank=True, default='', max_length=255, verbose_name='название из УПД')),
                ('serial_number', models.CharField(blank=True, default='', max_length=128, verbose_name='заводской №')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='plume.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='plume.item')),
                ('kitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='plume.kitting')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='plume.lot')),
            ],
            options={
                'verbose_name': 'партия',
                'verbose_name_plural': 'партии',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлена'), ('cancelled', 'Отменена')], default='draft', max_length=16, verbose_name='статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата (начало переговоров)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='примечание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'закупка (план)',
                'verbose_name_plural': 'закупки (план)',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='бюджет на материалы')),
                ('kind', models.CharField(choices=[('external', 'Внешний (НИР/контракт)'), ('internal_stock', 'Собственный склад (белые)'), ('internal_writeoff', 'Свободные неучтённые (серые)')], default='external', max_length=20, verbose_name='вид')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=16, verbose_name='статус')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='начат')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='закрыт')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('partial', 'Частично получен'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='draft', max_length=16, verbose_name='статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата (оформление)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='примечание')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plume.procurement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plume.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='№ требования')),
                ('date', models.DateField(verbose_name='дата')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='plume.project', verbose_name='проект-получатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'требование',
                'verbose_name_plural': 'требования',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('inn', models.CharField(blank=True, default='', max_length=16, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('number', models.CharField(max_length=64, verbose_name='№ накладной')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='plume.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'передача',
                'verbose_name_plural': 'передачи',
            },
        ),
        migrations.CreateModel(
            name='Writeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='№ акта')),
                ('date', models.DateField(verbose_name='дата')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='причина')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='plume.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'списания',
            },
        ),
        migrations.CreateModel(
            name='WriteoffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_lines', to='plume.lot')),
                ('writeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.writeoff')),
            ],
            options={
                'verbose_name': 'строка списания',
                'verbose_name_plural': 'строки списания',
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='отображаемое имя')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='plume.lot')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.transfer')),
            ],
            options={
                'verbose_name': 'строка передачи',
                'verbose_name_plural': 'строки передачи',
            },
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.requisition')),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='plume.lot', verbose_name='лот-источник')),
            ],
            options={
                'verbose_name': 'строка требования',
                'verbose_name_plural': 'строки требования',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='№ УПД')),
                ('date', models.DateField(verbose_name='дата')),
                ('approved', models.BooleanField(default=False, verbose_name='сверено со сканом (замок)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='plume.project')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='plume.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='plume.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'приход (УПД)',
                'verbose_name_plural': 'приходы (УПД)',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='заказано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='plume.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.purchase')),
            ],
            options={
                'verbose_name': 'строка заказа',
                'verbose_name_plural': 'строки заказа',
            },
        ),
        migrations.CreateModel(
            name='ProjectDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='plume.project')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demanded_in', to='plume.item')),
            ],
            options={
                'verbose_name': 'потребность проекта',
                'verbose_name_plural': 'потребности проектов',
            },
        ),
        migrations.CreateModel(
            name='ProcurementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во (итог)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.item')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.procurement')),
            ],
            options={
                'verbose_name': 'строка закупки',
                'verbose_name_plural': 'строки закупки',
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='plume.project', verbose_name='home-проект'),
        ),
        migrations.AddField(
            model_name='lot',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='plume.receipt'),
        ),
        migrations.AddField(
            model_name='lot',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='plume.requisition'),
        ),
        migrations.CreateModel(
            name='KittingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата пайки')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.item')),
                ('kitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plume.kitting')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitting_lines', to='plume.lot')),
            ],
            options={
                'verbose_name': 'строка комплектации',
                'verbose_name_plural': 'строки комплектации',
            },
        ),
        migrations.AddField(
            model_name='kitting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kittings', to='plume.project'),
        ),
        migrations.AddField(
            model_name='kitting',
            name='target_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kittings', to='plume.item'),
        ),
        migrations.AddField(
            model_name='kitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kittings', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='plume.project'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='позиция')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='plume.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='plume.item')),
            ],
            options={
                'verbose_name': 'строка BOM',
                'verbose_name_plural': 'строки BOM',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='файл')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='имя файла')),
                ('size', models.IntegerField(default=0, verbose_name='размер, байт')),
                ('content_type', models.CharField(blank=True, default='', max_length=64, verbose_name='тип')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.inventory')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.item')),
                ('kitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.kitting')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.receipt')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.requisition')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
                ('writeoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plume.writeoff')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEIPT', 'Приход'), ('ISSUE', 'Расход'), ('RETURN', 'Возврат')], max_length=16, verbose_name='тип')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='кол-во (со знаком)')),
                ('source_type', models.CharField(max_length=32, verbose_name='тип документа-источника')),
                ('source_id', models.IntegerField(verbose_name='id документа-источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='штамп вставки')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plume.location')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='plume.lot')),
            ],
            options={
                'verbose_name': 'движение склада',
                'verbose_name_plural': 'движения склада',
                'indexes': [models.Index(fields=['lot'], name='plume_stock_lot_id_7c3612_idx'), models.Index(fields=['location'], name='plume_stock_locatio_3b042c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.UniqueConstraint(fields=('purchase', 'item'), name='purchaseline_uniq_purchase_item'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt__isnull', False), ('kitting__isnull', True), ('inventory__isnull', True), ('requisition__isnull', True)), models.Q(('kitting__isnull', False), ('receipt__isnull', True), ('inventory__isnull', True), ('requisition__isnull', True)), models.Q(('inventory__isnull', False), ('receipt__isnull', True), ('kitting__isnull', True), ('requisition__isnull', True)), models.Q(('requisition__isnull', False), ('receipt__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True)), _connector='OR'), name='lot_exactly_one_origin'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('parent', 'component'), name='bomline_uniq_parent_component'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('receipt__isnull', True), ('transfer__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True), ('writeoff__isnull', True), ('requisition__isnull', True)), models.Q(('receipt__isnull', False), ('item__isnull', True), ('transfer__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True), ('writeoff__isnull', True), ('requisition__isnull', True)), models.Q(('transfer__isnull', False), ('item__isnull', True), ('receipt__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True), ('writeoff__isnull', True), ('requisition__isnull', True)), models.Q(('kitting__isnull', False), ('item__isnull', True), ('receipt__isnull', True), ('transfer__isnull', True), ('inventory__isnull', True), ('writeoff__isnull', True), ('requisition__isnull', True)), models.Q(('inventory__isnull', False), ('item__isnull', True), ('receipt__isnull', True), ('transfer__isnull', True), ('kitting__isnull', True), ('writeoff__isnull', True), ('requisition__isnull', True)), models.Q(('writeoff__isnull', False), ('item__isnull', True), ('receipt__isnull', True), ('transfer__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True), ('requisition__isnull', True)), models.Q(('requisition__isnull', False), ('item__isnull', True), ('receipt__isnull', True), ('transfer__isnull', True), ('kitting__isnull', True), ('inventory__isnull', True), ('writeoff__isnull', True)), _connector='OR'), name='attachment_exactly_one_owner'),
        ),
    ]
