# Generated by Django 6.0.6 on 2026-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='отгружено (замок)'),
        ),
    ]
