# Generated by Django 6.0.6 on 2026-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=16, verbose_name='статус'),
        ),
    ]
