# Generated by Django 6.0.6 on 2026-07-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['code'], 'verbose_name': 'склад', 'verbose_name_plural': 'склады'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'поставка', 'verbose_name_plural': 'поставки'},
        ),
    ]
