# Generated by Django 6.0.6 on 2026-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='attachments/%Y/%m/', verbose_name='файл'),
        ),
    ]
