# Generated by Django 6.0.6 on 2026-08-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0002_alter_attachment_content_type_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='projects',
        ),
    ]
