# Generated by Django 6.0.6 on 2026-07-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0004_locked_bool_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='plume.counterparty', verbose_name='контрагент'),
        ),
    ]
