# Generated by Django 6.0.6 on 2026-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0006_code_description_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='produced',
            new_name='native',
        ),
        migrations.AddField(
            model_name='item',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='из библиотеки'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('synced', False), ('native', False), _connector='OR'), name='item_synced_implies_not_native'),
        ),
    ]
