# Generated by Django 6.0.6 on 2026-07-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0007_lift_common_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('stockdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plume.stockdocument')),
            ],
            options={
                'verbose_name': 'перемещение',
                'verbose_name_plural': 'перемещения',
            },
            bases=('plume.stockdocument',),
        ),
    ]
