# Generated by Django 6.0.6 on 2026-07-25 10:47

from django.db import migrations, models


def clear_stale_locks(apps, schema_editor):
    """Снять стухший замок у библиотечных (`synced`) перед добавлением инварианта
    `synced ⟹ not locked`. Наследие волны 17: старый синк ставил `locked=True` как
    маркер «из библиотеки», а первый синк после Ф3a пометил их `synced=True`, замок не
    сняв. Теперь библиотечное защищено матрицей «правь только цену», а не фиксацией."""
    Item = apps.get_model('plume', 'Item')
    Item.objects.filter(synced=True, locked=True).update(locked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('plume', '0007_item_axes_native_synced'),
    ]

    operations = [
        # Сперва данные (иначе AddConstraint упадёт на залоченных библиотечных),
        # затем сам инвариант. Reverse — no-op: какие были залочены, не восстановить.
        migrations.RunPython(clear_stale_locks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('synced', False), ('locked', False), _connector='OR'), name='item_synced_implies_not_locked'),
        ),
    ]
